export const notes = [
  {
    id: `${self.crypto.randomUUID()}`,
    name: "Make a sandwitch",
    createDate: "12.12.2023",
    category: "Task",
    content: "SomeContent 12.12.2021",
    dates: "12/12/2021",
    state: "archived",
  },
  {
    id: `${self.crypto.randomUUID()}`,
    name: "I am bad",
    createDate: "12.12.2023",
    category: "Thoughts",
    content: "It seems like my stomach ill",
    dates: "",
    state: "active",
  },
  {
    id: `${self.crypto.randomUUID()}`,
    name: "Check out",
    createDate: "12.12.2023",
    category: "Idea",
    content: "From university",
    dates: "",
    state: "active",
  },
  {
    id: `${self.crypto.randomUUID()}`,
    name: "name4",
    createDate: "12.12.2023",
    category: "Thoughts",
    content: "SomeContttttttttttttttttent 12.12.2021",
    dates: "12/12/2021",
    state: "active",
  },
  {
    id: `${self.crypto.randomUUID()}`,
    name: "name5",
    createDate: "12.12.2023",
    category: "Thoughts",
    content: "SomeContent 12.12.2021",
    dates: "12/12/2021",
    state: "active",
  },
  {
    id: `${self.crypto.randomUUID()}`,
    name: "name6",
    createDate: "12.12.2023",
    category: "Thoughts",
    content: "SomeContent 12.12.2021",
    dates: "12/12/2021",
    state: "archived",
  },
  {
    id: `${self.crypto.randomUUID()}`,
    name: "name7",
    createDate: "12.12.2023",
    category: "Quote",
    content: "SomeContent 12.12.2021",
    dates: "12/12/2021",
    state: "archived",
  },
];
